{"name":"Df TPC-H region","ppdf:dataflowId":"44fb498a-c3ce-4ca4-a2f2-cd68ee0bbac7","ppdf:owner":{"tenantId":"e2c852c9-a592-4198-8b26-76695664931e","userId":"aefcfa2c-e7f1-4392-b701-cffd823e827d"},"ppdf:fastCopy":false,"version":"1.0","culture":"en-US","modifiedTime":"2023-05-27T18:59:17.0247211+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Customers1":{"queryId":"1d54f224-d458-41b5-8be4-053e01cff727","queryName":"Customers1","loadEnabled":true},"tcp-h Region":{"queryId":"b7ee3a9f-96f4-40de-8ba6-df83c83971b2","queryName":"tcp-h Region","loadEnabled":true},"DestinationForWriteToDatabaseTableFrom_Customers1":{"queryId":"ff10b164-76c1-434c-80f5-0bb0d4ffba91","queryName":"DestinationForWriteToDatabaseTableFrom_Customers1"},"WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_Customers1":{"queryId":"e64cd96c-def3-4e45-a533-fc81ef9c890c","queryName":"WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_Customers1"},"TransformForOutputToDatabaseTableFrom_Customers1":{"queryId":"390697db-c54b-4b81-8f0b-e923489d5f58","queryName":"TransformForOutputToDatabaseTableFrom_Customers1"},"DefaultModelStorage":{"queryId":"06044491-daa4-4568-8402-6a3bbb6bb495","queryName":"DefaultModelStorage"}},"document":"section Section1;\r\n[Staging = \"DefaultModelStorage\"]\r\nshared Customers1 = let\r\n  Source = AzureStorage.Blobs(\"stfabrictpch\"),\r\n  #\"Navigation 1\" = Source{[Name = \"tcphfabric\"]}[Data],\r\n  Navigation = #\"Navigation 1\"{[#\"Folder Path\" = \"https://stfabrictpch.blob.core.windows.net/tcphfabric/\", Name = \"files/region.tbl.csv\"]}[Content],\r\n  #\"Imported CSV\" = Csv.Document(Navigation, [Delimiter = \"|\", Columns = 4, QuoteStyle = QuoteStyle.None]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Imported CSV\", {{\"Column1\", Int64.Type}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Changed column type\", {{\"Column1\", \"RegionKey\"}, {\"Column2\", \"Name\"}, {\"Column3\", \"Comment\"}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Renamed columns\", {\"Column4\"})\r\nin\r\n  #\"Removed columns\";\r\nshared #\"tcp-h Region\" = let\r\n  Source = AzureStorage.Blobs(\"stfabrictpch\"),\r\n  Navigation = Source{[Name = \"tcphfabric\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[#\"Folder Path\" = \"https://stfabrictpch.blob.core.windows.net/tcphfabric/\", Name = \"files/region.tbl.csv\"]}[Content],\r\n  #\"Imported CSV\" = Csv.Document(#\"Navigation 1\", [Delimiter = \"|\", Columns = 4, QuoteStyle = QuoteStyle.None]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Imported CSV\", {{\"Column1\", Int64.Type}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared DestinationForWriteToDatabaseTableFrom_Customers1 = let\r\n  Pattern = Lakehouse.Contents([]),\r\n  Navigation_1 = Pattern{[workspaceId = \"67b89416-5490-4a2c-9133-3d0cf579aa1f\"]}[Data],\r\n  Navigation_2 = Navigation_1{[lakehouseId = \"832d2d26-0b61-472a-9028-9d2860e15071\"]}[Data],\r\n  TableNavigation = Navigation_2{[Id = \"Region\", ItemKind = \"Table\"]}?[Data]?,\r\n  Table = NavigationTable.CreateTableOnDemand(TableNavigation, #table(type table[RegionKey = nullable Int64.Type, Name = nullable text, Comment = nullable text], {}), [DeleteWhenEmpty = true])\r\nin\r\n  Table;\r\n[Staging = \"DefaultModelStorage\"]\r\nshared WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_Customers1 = let\r\n  WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_Customers1 = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = DestinationForWriteToDatabaseTableFrom_Customers1], (txn) => {TableAction.DeleteRows(txn[Target]), TableAction.InsertRows(txn[Target], TransformForOutputToDatabaseTableFrom_Customers1), Action.DoNothing}))\r\nin\r\n  WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_Customers1;\r\nshared TransformForOutputToDatabaseTableFrom_Customers1 = let\r\n    SourceTable = Table.SelectColumns(Customers1, {\"RegionKey\", \"Name\", \"Comment\"})\r\nin\r\n    SourceTable;\r\nshared DefaultModelStorage = let\r\n  DefaultModelStorage = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultModelStorage;\r\n","connectionOverrides":[{"path":"https://stfabrictpch.blob.core.windows.net/","kind":"AzureBlobs","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"AzureBlobs\",\"path\":\"https://stfabrictpch.blob.core.windows.net/\"}","audience":null},{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"Customers1","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Customers1.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"RegionKey","dataType":"int64"},{"name":"Name","dataType":"string"},{"name":"Comment","dataType":"string"}]},{"$type":"LocalEntity","name":"tcp-h Region","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"tcp-h%20Region.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"Column1","dataType":"int64"},{"name":"Column2","dataType":"string"},{"name":"Column3","dataType":"string"},{"name":"Column4","dataType":"string"}]}]}