{"name":"Df TPC-H Nations","ppdf:dataflowId":"814b7e9b-2781-4def-95e9-24288c276c71","ppdf:owner":{"tenantId":"e2c852c9-a592-4198-8b26-76695664931e","userId":"aefcfa2c-e7f1-4392-b701-cffd823e827d"},"ppdf:fastCopy":false,"version":"1.0","culture":"en-US","modifiedTime":"2023-05-27T19:00:34.5214253+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"TPC-H Nations":{"queryId":"6a3f67ea-6184-44df-ad8e-3f65a136de08","queryName":"TPC-H Nations","loadEnabled":true},"DestinationForWriteToDatabaseTableFrom_TPC-H Nations":{"queryId":"b6d6eb2f-6d72-4866-b81b-e3a664b80100","queryName":"DestinationForWriteToDatabaseTableFrom_TPC-H Nations"},"WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_TPC-H Nations":{"queryId":"f71f5891-6045-438b-83f1-110958da5dc6","queryName":"WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_TPC-H Nations"},"TransformForOutputToDatabaseTableFrom_TPC-H Nations":{"queryId":"5361c41f-182c-42dc-93a9-62746e44a68f","queryName":"TransformForOutputToDatabaseTableFrom_TPC-H Nations"},"DefaultModelStorage":{"queryId":"120c395d-b445-4606-a887-672a8f9f08be","queryName":"DefaultModelStorage"}},"document":"section Section1;\r\n[Staging = \"DefaultModelStorage\"]\r\nshared #\"TPC-H Nations\" = let\r\n  Source = AzureStorage.Blobs(\"stfabrictpch\"),\r\n  Navigation = Source{[Name = \"tcphfabric\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[#\"Folder Path\" = \"https://stfabrictpch.blob.core.windows.net/tcphfabric/\", Name = \"files/nation.csv\"]}[Content],\r\n  #\"Imported CSV\" = Csv.Document(#\"Navigation 1\", [Delimiter = \"|\", Columns = 5, QuoteStyle = QuoteStyle.None]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Imported CSV\", {{\"Column1\", Int64.Type}, {\"Column2\", type text}, {\"Column3\", Int64.Type}, {\"Column4\", type text}, {\"Column5\", type text}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Changed column type\", {{\"Column1\", \"NationKey\"}, {\"Column2\", \"Name\"}, {\"Column3\", \"RegionKey\"}, {\"Column4\", \"Comment\"}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Renamed columns\", {\"Column5\"})\r\nin\r\n  #\"Removed columns\";\r\nshared #\"DestinationForWriteToDatabaseTableFrom_TPC-H Nations\" = let\r\n  Pattern = Lakehouse.Contents([]),\r\n  Navigation_1 = Pattern{[workspaceId = \"67b89416-5490-4a2c-9133-3d0cf579aa1f\"]}[Data],\r\n  Navigation_2 = Navigation_1{[lakehouseId = \"832d2d26-0b61-472a-9028-9d2860e15071\"]}[Data],\r\n  TableNavigation = Navigation_2{[Id = \"Nation\", ItemKind = \"Table\"]}?[Data]?,\r\n  Table = NavigationTable.CreateTableOnDemand(TableNavigation, #table(type table[NationKey = nullable Int64.Type, Name = nullable text, RegionKey = nullable Int64.Type, Comment = nullable text], {}), [DeleteWhenEmpty = true])\r\nin\r\n  Table;\r\n[Staging = \"DefaultModelStorage\"]\r\nshared #\"WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_TPC-H Nations\" = let\r\n  #\"WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_TPC-H Nations\" = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = #\"DestinationForWriteToDatabaseTableFrom_TPC-H Nations\"], (txn) => {TableAction.DeleteRows(txn[Target]), TableAction.InsertRows(txn[Target], #\"TransformForOutputToDatabaseTableFrom_TPC-H Nations\"), Action.DoNothing}))\r\nin\r\n  #\"WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_TPC-H Nations\";\r\nshared #\"TransformForOutputToDatabaseTableFrom_TPC-H Nations\" = let\r\n    SourceTable = Table.SelectColumns(#\"TPC-H Nations\", {\"NationKey\", \"Name\", \"RegionKey\", \"Comment\"})\r\nin\r\n    SourceTable;\r\nshared DefaultModelStorage = let\r\n  DefaultModelStorage = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultModelStorage;\r\n","connectionOverrides":[{"path":"https://stfabrictpch.blob.core.windows.net/","kind":"AzureBlobs","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"AzureBlobs\",\"path\":\"https://stfabrictpch.blob.core.windows.net/\"}","audience":null},{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"TPC-H Nations","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"TPC-H%20Nations.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"NationKey","dataType":"int64"},{"name":"Name","dataType":"string"},{"name":"RegionKey","dataType":"int64"},{"name":"Comment","dataType":"string"}]}]}