{"name":"Df TPC-H Customer","description":"Just File nr. 2, not seen a way to combine files (yet).","ppdf:dataflowId":"566700f9-d4fa-4dcc-86e6-3720396c4f60","ppdf:owner":{"tenantId":"e2c852c9-a592-4198-8b26-76695664931e","userId":"aefcfa2c-e7f1-4392-b701-cffd823e827d"},"ppdf:fastCopy":false,"version":"1.0","culture":"en-US","modifiedTime":"2023-05-27T19:06:50.1916677+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"tcphfabric":{"queryId":"541f850b-0d34-4155-b8a4-76f7b4653141","queryName":"tcphfabric","loadEnabled":true},"DestinationForWriteToDatabaseTableFrom_tcphfabric":{"queryId":"65365e03-5ac6-4066-8963-cfce77ced4a7","queryName":"DestinationForWriteToDatabaseTableFrom_tcphfabric"},"WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_tcphfabric":{"queryId":"0799fc69-160d-4295-8564-bb6893b78c08","queryName":"WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_tcphfabric"},"TransformForOutputToDatabaseTableFrom_tcphfabric":{"queryId":"2acf0fae-dfee-4b54-a540-2b1fd8a2599c","queryName":"TransformForOutputToDatabaseTableFrom_tcphfabric"},"DefaultModelStorage":{"queryId":"62968738-a910-4258-85a5-84f215c6be61","queryName":"DefaultModelStorage"}},"document":"section Section1;\r\n[Staging = \"DefaultModelStorage\"]\r\nshared tcphfabric = let\r\n  Source = AzureStorage.Blobs(\"stfabrictpch\"),\r\n  Navigation = Source{[Name = \"tcphfabric\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[#\"Folder Path\" = \"https://stfabrictpch.blob.core.windows.net/tcphfabric/\", Name = \"files/customer.tbl.2.csv\"]}[Content],\r\n  #\"Imported CSV\" = Csv.Document(#\"Navigation 1\", [Delimiter = \"|\", Columns = 9, QuoteStyle = QuoteStyle.None]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Imported CSV\", {{\"Column1\", Int64.Type}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", Int64.Type}, {\"Column5\", type text}, {\"Column6\", type number}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Changed column type\", {{\"Column1\", \"CustKey\"}, {\"Column2\", \"Name\"}, {\"Column3\", \"Address\"}, {\"Column4\", \"NationKey\"}, {\"Column5\", \"Phone\"}, {\"Column6\", \"Acctbal\"}, {\"Column7\", \"Mktsegment\"}, {\"Column8\", \"Comment\"}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Renamed columns\", {\"Column9\"})\r\nin\r\n  #\"Removed columns\";\r\nshared DestinationForWriteToDatabaseTableFrom_tcphfabric = let\r\n  Pattern = Lakehouse.Contents([]),\r\n  Navigation_1 = Pattern{[workspaceId = \"67b89416-5490-4a2c-9133-3d0cf579aa1f\"]}[Data],\r\n  Navigation_2 = Navigation_1{[lakehouseId = \"832d2d26-0b61-472a-9028-9d2860e15071\"]}[Data],\r\n  TableNavigation = Navigation_2{[Id = \"Customer\", ItemKind = \"Table\"]}?[Data]?,\r\n  Table = NavigationTable.CreateTableOnDemand(TableNavigation, #table(type table[CustKey = nullable Int64.Type, Name = nullable text, Address = nullable text, NationKey = nullable Int64.Type, Phone = nullable text, Acctbal = nullable number, Mktsegment = nullable text, Comment = nullable text], {}), [DeleteWhenEmpty = true])\r\nin\r\n  Table;\r\n[Staging = \"DefaultModelStorage\"]\r\nshared WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_tcphfabric = let\r\n  WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_tcphfabric = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = DestinationForWriteToDatabaseTableFrom_tcphfabric], (txn) => {TableAction.DeleteRows(txn[Target]), TableAction.InsertRows(txn[Target], TransformForOutputToDatabaseTableFrom_tcphfabric), Action.DoNothing}))\r\nin\r\n  WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_tcphfabric;\r\nshared TransformForOutputToDatabaseTableFrom_tcphfabric = let\r\n    SourceTable = Table.SelectColumns(tcphfabric, {\"CustKey\", \"Name\", \"Address\", \"NationKey\", \"Phone\", \"Acctbal\", \"Mktsegment\", \"Comment\"})\r\nin\r\n    SourceTable;\r\nshared DefaultModelStorage = let\r\n  DefaultModelStorage = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultModelStorage;\r\n","connectionOverrides":[{"path":"https://stfabrictpch.blob.core.windows.net/","kind":"AzureBlobs","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"AzureBlobs\",\"path\":\"https://stfabrictpch.blob.core.windows.net/\"}","audience":null},{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"tcphfabric","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"tcphfabric.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"CustKey","dataType":"int64"},{"name":"Name","dataType":"string"},{"name":"Address","dataType":"string"},{"name":"NationKey","dataType":"int64"},{"name":"Phone","dataType":"string"},{"name":"Acctbal","dataType":"decimal"},{"name":"Mktsegment","dataType":"string"},{"name":"Comment","dataType":"string"}]}]}