{"name":"dfgen2_order_lineitem","ppdf:dataflowId":"f0598027-1966-4c0c-8fdd-bc9e354dc322","ppdf:owner":{"tenantId":"e2c852c9-a592-4198-8b26-76695664931e","userId":"aefcfa2c-e7f1-4392-b701-cffd823e827d"},"ppdf:fastCopy":false,"version":"1.0","culture":"en-US","modifiedTime":"2023-12-28T19:58:54.3343599+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"LineItems":{"queryId":"7c4cb837-a962-4578-91c2-f19e153618c2","queryName":"LineItems","loadEnabled":true},"Orders":{"queryId":"c0fcb907-3863-4438-a212-329fa06c3892","queryName":"Orders","loadEnabled":true},"LineItems_DataDestination":{"queryId":"4c6a6865-70a1-478f-9c3f-b58afa8d3403","queryName":"LineItems_DataDestination"},"LineItems_WriteToDataDestination":{"queryId":"2cfdd28c-ba4b-46f5-a791-19f7706eb291","queryName":"LineItems_WriteToDataDestination"},"LineItems_TransformForWriteToDataDestination":{"queryId":"f494c40f-0d99-4e29-a09b-a2a63a56d9e9","queryName":"LineItems_TransformForWriteToDataDestination"},"DefaultStaging":{"queryId":"e5789f70-e0ab-4513-ab06-cfc11ab10184","queryName":"DefaultStaging"}},"document":"section Section1;\r\n[Staging = \"DefaultStaging\"]\r\nshared LineItems = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"67b89416-5490-4a2c-9133-3d0cf579aa1f\"]}[Data]{[lakehouseId = \"832d2d26-0b61-472a-9028-9d2860e15071\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"Files\", ItemKind = \"Folder\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"TCPH-RAW\"]}[Content],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"LineItems\"]}[Content],\r\n  Navigation = #\"Navigation 3\"{[Name = \"lineitem.tbl_00000.1.parquet\"]}[Content],\r\n  #\"Imported Parquet\" = Parquet.Document(Navigation),\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Imported Parquet\", {\"l_orderkey\"}, Orders, {\"o_orderkey\"}, \"Orders\", JoinKind.Inner),\r\n  #\"Expanded Orders\" = Table.ExpandTableColumn(#\"Merged queries\", \"Orders\", {\"o_orderkey\", \"o_custkey\", \"o_orderstatus\", \"o_totalprice\", \"o_orderdate\", \"o_orderpriority\", \"o_clerk\", \"o_shippriority\", \"o_comment\"}, {\"o_orderkey\", \"o_custkey\", \"o_orderstatus\", \"o_totalprice\", \"o_orderdate\", \"o_orderpriority\", \"o_clerk\", \"o_shippriority\", \"o_comment\"})\r\nin\r\n  #\"Expanded Orders\";\r\nshared Orders = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"67b89416-5490-4a2c-9133-3d0cf579aa1f\"]}[Data]{[lakehouseId = \"832d2d26-0b61-472a-9028-9d2860e15071\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"Files\", ItemKind = \"Folder\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"TCPH-RAW\"]}[Content],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"Orders\"]}[Content],\r\n  Navigation = #\"Navigation 3\"{[Name = \"orders.tbl_00000.1.parquet\"]}[Content],\r\n  #\"Imported Parquet\" = Parquet.Document(Navigation)\r\nin\r\n  #\"Imported Parquet\";\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\nshared LineItems_DataDestination = let\r\n  Pattern = Lakehouse.Contents([]),\r\n  Navigation_1 = Pattern{[workspaceId = \"67b89416-5490-4a2c-9133-3d0cf579aa1f\"]}[Data],\r\n  Navigation_2 = Navigation_1{[lakehouseId = \"832d2d26-0b61-472a-9028-9d2860e15071\"]}[Data],\r\n  TableNavigation = Navigation_2{[Id = \"LineItemsdf\", ItemKind = \"Table\"]}?[Data]?,\r\n  Table = NavigationTable.CreateTableOnDemand(TableNavigation, #table(type table[l_orderkey = nullable text, l_partkey = nullable text, l_suppkey = nullable text, l_linenumber = nullable text, l_quantity = nullable text, l_extendedprice = nullable text, l_discount = nullable text, l_tax = nullable text, l_returnflag = nullable text, l_linestatus = nullable text, l_shipdate = nullable text, l_commitdate = nullable text, l_receiptdate = nullable text, l_shipinstruct = nullable text, l_shipmode = nullable text, l_comment = nullable text, o_orderkey = nullable text, o_custkey = nullable text, o_orderstatus = nullable text, o_totalprice = nullable text, o_orderdate = nullable text, o_orderpriority = nullable text, o_clerk = nullable text, o_shippriority = nullable text, o_comment = nullable text], {}), [DeleteWhenEmpty = true])\r\nin\r\n  Table;\r\n[Staging = \"DefaultStaging\"]\r\nshared LineItems_WriteToDataDestination = let\r\n  LineItems_WriteToDataDestination = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = LineItems_DataDestination], (txn) => {TableAction.DeleteRows(txn[Target]), () => TableAction.InsertRows(txn[Target], LineItems_TransformForWriteToDataDestination), Action.DoNothing}))\r\nin\r\n  LineItems_WriteToDataDestination;\r\nshared LineItems_TransformForWriteToDataDestination = let\r\n    SourceTable = Table.SelectColumns(LineItems, {\"l_orderkey\", \"l_partkey\", \"l_suppkey\", \"l_linenumber\", \"l_quantity\", \"l_extendedprice\", \"l_discount\", \"l_tax\", \"l_returnflag\", \"l_linestatus\", \"l_shipdate\", \"l_commitdate\", \"l_receiptdate\", \"l_shipinstruct\", \"l_shipmode\", \"l_comment\", \"o_orderkey\", \"o_custkey\", \"o_orderstatus\", \"o_totalprice\", \"o_orderdate\", \"o_orderpriority\", \"o_clerk\", \"o_shippriority\", \"o_comment\"})\r\nin\r\n    SourceTable;\r\n","connectionOverrides":[{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"LineItems","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"LineItems.parquet"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"},{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"l_orderkey","dataType":"string"},{"name":"l_partkey","dataType":"string"},{"name":"l_suppkey","dataType":"string"},{"name":"l_linenumber","dataType":"string"},{"name":"l_quantity","dataType":"string"},{"name":"l_extendedprice","dataType":"string"},{"name":"l_discount","dataType":"string"},{"name":"l_tax","dataType":"string"},{"name":"l_returnflag","dataType":"string"},{"name":"l_linestatus","dataType":"string"},{"name":"l_shipdate","dataType":"string"},{"name":"l_commitdate","dataType":"string"},{"name":"l_receiptdate","dataType":"string"},{"name":"l_shipinstruct","dataType":"string"},{"name":"l_shipmode","dataType":"string"},{"name":"l_comment","dataType":"string"},{"name":"o_orderkey","dataType":"string"},{"name":"o_custkey","dataType":"string"},{"name":"o_orderstatus","dataType":"string"},{"name":"o_totalprice","dataType":"string"},{"name":"o_orderdate","dataType":"string"},{"name":"o_orderpriority","dataType":"string"},{"name":"o_clerk","dataType":"string"},{"name":"o_shippriority","dataType":"string"},{"name":"o_comment","dataType":"string"}]},{"$type":"LocalEntity","name":"Orders","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Orders.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"o_orderkey","dataType":"string"},{"name":"o_custkey","dataType":"string"},{"name":"o_orderstatus","dataType":"string"},{"name":"o_totalprice","dataType":"string"},{"name":"o_orderdate","dataType":"string"},{"name":"o_orderpriority","dataType":"string"},{"name":"o_clerk","dataType":"string"},{"name":"o_shippriority","dataType":"string"},{"name":"o_comment","dataType":"string"}]}]}