{"name":"Load DimCustomer","ppdf:dataflowId":"99bf84c1-ced8-4549-93b8-3f651cd70723","ppdf:owner":{"tenantId":"e2c852c9-a592-4198-8b26-76695664931e","userId":"aefcfa2c-e7f1-4392-b701-cffd823e827d"},"ppdf:fastCopy":false,"version":"1.0","culture":"en-US","modifiedTime":"2023-05-24T19:32:28.188887+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"dimension_customer":{"queryId":"9da8cf9e-22d9-4b4c-a42b-003012d45154","queryName":"dimension_customer","loadEnabled":true},"DestinationForWriteToDatabaseTableFrom_dimension_customer":{"queryId":"386d21a5-9cb5-4488-907a-e937b5befa49","queryName":"DestinationForWriteToDatabaseTableFrom_dimension_customer"},"WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_dimension_custome":{"queryId":"64eaa2a3-2ba0-42ca-aff3-352e2a020f00","queryName":"WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_dimension_custome"},"TransformForOutputToDatabaseTableFrom_dimension_customer":{"queryId":"582ae13b-bf6b-48c3-b4c6-a04b338e15a2","queryName":"TransformForOutputToDatabaseTableFrom_dimension_customer"},"DefaultModelStorage":{"queryId":"e0b9563d-3709-4a09-aa8c-a95ab84515c1","queryName":"DefaultModelStorage"}},"document":"section Section1;\r\n[Staging = \"DefaultModelStorage\"]\r\nshared dimension_customer = let\r\n  Source = Csv.Document(Web.Contents(\"https://rgnewstarsofdatadiag.blob.core.windows.net/planesdwh/dimension_customer.csv\"), [Delimiter = \",\", Columns = 11, Encoding = 65001, QuoteStyle = QuoteStyle.None]),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CustomerKey\", Int64.Type}, {\"WWICustomerID\", Int64.Type}, {\"Customer\", type text}, {\"BillToCustomer\", type text}, {\"Category\", type text}, {\"BuyingGroup\", type text}, {\"PrimaryContact\", type text}, {\"PostalCode\", type text}, {\"ValidFrom\", type datetime}, {\"ValidTo\", type datetime}, {\"LineageKey\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared DestinationForWriteToDatabaseTableFrom_dimension_customer = let\r\n  Pattern = Lakehouse.Contents([]),\r\n  Navigation_1 = Pattern{[workspaceId = \"67b89416-5490-4a2c-9133-3d0cf579aa1f\"]}[Data],\r\n  Navigation_2 = Navigation_1{[lakehouseId = \"832d2d26-0b61-472a-9028-9d2860e15071\"]}[Data],\r\n  TableNavigation = Navigation_2{[Id = \"dimension_customer\", ItemKind = \"Table\"]}?[Data]?,\r\n  Table = NavigationTable.CreateTableOnDemand(TableNavigation, #table(type table[CustomerKey = nullable Int64.Type, WWICustomerID = nullable Int64.Type, Customer = nullable text, BillToCustomer = nullable text, Category = nullable text, BuyingGroup = nullable text, PrimaryContact = nullable text, PostalCode = nullable text, ValidFrom = nullable datetime, ValidTo = nullable datetime, LineageKey = nullable Int64.Type], {}), [DeleteWhenEmpty = true])\r\nin\r\n  Table;\r\n[Staging = \"DefaultModelStorage\"]\r\nshared WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_dimension_custome = let\r\n  WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_dimension_custome = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = DestinationForWriteToDatabaseTableFrom_dimension_customer], (txn) => {TableAction.DeleteRows(txn[Target]), TableAction.InsertRows(txn[Target], TransformForOutputToDatabaseTableFrom_dimension_customer), Action.DoNothing}))\r\nin\r\n  WriteToDatabaseTableFrom_TransformForOutputToDatabaseTableFrom_dimension_custome;\r\nshared TransformForOutputToDatabaseTableFrom_dimension_customer = let\r\n    SourceTable = Table.SelectColumns(dimension_customer, {\"CustomerKey\", \"WWICustomerID\", \"Customer\", \"BillToCustomer\", \"Category\", \"BuyingGroup\", \"PrimaryContact\", \"PostalCode\", \"ValidFrom\", \"ValidTo\", \"LineageKey\"})\r\nin\r\n    SourceTable;\r\nshared DefaultModelStorage = let\r\n  DefaultModelStorage = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultModelStorage;\r\n","connectionOverrides":[{"path":"https://rgnewstarsofdatadiag.blob.core.windows.net/planesdwh/dimension_customer.csv","kind":"Web","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Web\",\"path\":\"https://rgnewstarsofdatadiag.blob.core.windows.net/planesdwh/dimension_customer.csv\"}","audience":null},{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"dimension_customer","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"dimension_customer.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"CustomerKey","dataType":"int64"},{"name":"WWICustomerID","dataType":"int64"},{"name":"Customer","dataType":"string"},{"name":"BillToCustomer","dataType":"string"},{"name":"Category","dataType":"string"},{"name":"BuyingGroup","dataType":"string"},{"name":"PrimaryContact","dataType":"string"},{"name":"PostalCode","dataType":"string"},{"name":"ValidFrom","dataType":"dateTime"},{"name":"ValidTo","dataType":"dateTime"},{"name":"LineageKey","dataType":"int64"}]}]}